tasks:
  - name: terraform
    before: |
      source ./bin/install_terraform_cli.bash
      source ./bin/generate_tfrc_credentials.bash
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli.bash
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform